"""empty message

Revision ID: 252042fa6611
Revises: 904afc5df71e
Create Date: 2024-10-29 23:36:33.635501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '252042fa6611'
down_revision = '904afc5df71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=False))
        batch_op.drop_index('password_hash')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index('password_hash', ['password_hash'], unique=True)
        batch_op.drop_column('full_name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
