"""empty message

Revision ID: 904afc5df71e
Revises: ae8d7bd17e6b
Create Date: 2024-10-29 23:33:05.240020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904afc5df71e'
down_revision = 'ae8d7bd17e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['password_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
